
POST https://dbh.hkdir.no/api/Tabeller/hentJSONTabellData HTTP/1.1
Host: dbh.hkdir.no
Content-Type: application/json
Content-Length: 1216

{
    "tabell_id": 308,
    "api_versjon": 1,
    "statuslinje": "N",
    "begrensning": "*",
    "kodetekst": "N",
    "desimal_separator": ".",
    "groupBy": ["Emnekode", "Karakter"],
    "sortBy": ["Emnekode", "Karakter"],
    "variabler": ["*"],
    "filter": [
        {
            "variabel": "Institusjonskode",
            "selection": {
                "filter": "item",
                "values": [1150],
                "exclude": [""]
            }
        },
        {
            "variabel": "Årstall",
            "selection": {
                "filter": "item",
                "values": [2023],
                "exclude": [""]
            }
        },
        {
            "variabel": "Semester",
            "selection": {
                "filter": "item",
                "values": [1],
                "exclude": [""]
            }
        }
    ]
}
